// Generated by clash.py. Edit rules/*.yaml, not this file.
// Clash Verge Rev subscription extension script; no network requests or secrets.

const CUSTOM_RULES = __CUSTOM_RULES_JSON__;
const AI_GROUP = "Ai+";
const AI_STABLE_GROUP = "Ai稳定选择";
const AI_AUTO_GROUP = "Ai测速备用";
const LEGACY_AI_AUTO_GROUP = "Ai自动选择";
const SCHOLAR_GROUP = "学术搜索";
const FALLBACK_GROUP = "漏网之鱼";

// Bound short country codes to avoid matching ordinary words that contain hk/mo/tw.
const AI_EXCLUDE = /(?:🇭🇰|🇲🇴|🇹🇼|香港|澳门|澳門|台湾|台灣|hong[ -]?kong|macau|macao|taiwan|(?:^|[^a-z])(?:hk|mo|tw)(?:[^a-z]|$)|剩余流量|流量剩余|到期时间|过期时间|重置时间|套餐提示|订阅信息|(?:^|[\s|_-])(?:expire|traffic|sync|reset|官网|套餐|订阅|更新|客服|网址)(?:[\s:：|_-]|$))/i;

function groupByName(config, name) {
  return config["proxy-groups"].find((group) => group && group.name === name);
}

function eligibleAiNodes(config) {
  const seen = new Set();
  return config.proxies
    .filter((proxy) => proxy && typeof proxy.name === "string" && proxy.name)
    .filter((proxy) => String(proxy.type || "").toLowerCase() !== "direct")
    .map((proxy) => proxy.name)
    .filter((name) => !AI_EXCLUDE.test(name))
    .filter((name) => {
      if (seen.has(name)) return false;
      seen.add(name);
      return true;
    });
}

function fixProviderPaths(config) {
  const providers = config["rule-providers"];
  if (!providers || typeof providers !== "object") return;
  const apple = providers.Apple;
  const appleDev = providers.AppleDev;
  if (apple && appleDev && apple.path && apple.path === appleDev.path) {
    apple.path = "./providers/rule/Apple.yaml";
  }
}

function configureGroups(config) {
  if (!Array.isArray(config.proxies) || !Array.isArray(config["proxy-groups"])) {
    throw new Error("subscription must contain proxies and proxy-groups arrays");
  }

  const groups = config["proxy-groups"];
  const ai = groupByName(config, AI_GROUP);
  const fallback = groupByName(config, FALLBACK_GROUP);
  if (!ai || !fallback) {
    throw new Error(`subscription is missing ${!ai ? AI_GROUP : FALLBACK_GROUP}`);
  }

  const nodes = eligibleAiNodes(config);
  if (!nodes.length) throw new Error("no eligible non-HK/MO/TW AI nodes remain");

  config["proxy-groups"] = groups.filter(
    (group) => group && ![
      AI_STABLE_GROUP,
      AI_AUTO_GROUP,
      LEGACY_AI_AUTO_GROUP,
      SCHOLAR_GROUP,
    ].includes(group.name),
  );
  const aiIndex = config["proxy-groups"].findIndex((group) => group.name === AI_GROUP);

  const aiStable = {
    name: AI_STABLE_GROUP,
    type: "select",
    proxies: [...nodes],
  };
  const aiAuto = {
    name: AI_AUTO_GROUP,
    type: "url-test",
    proxies: [...nodes],
    url: "https://chatgpt.com/cdn-cgi/trace",
    interval: 300,
    tolerance: 50,
    lazy: true,
    timeout: 8000,
    "max-failed-times": 2,
    "expected-status": 200,
  };
  const scholar = {
    name: SCHOLAR_GROUP,
    type: "select",
    proxies: [AI_STABLE_GROUP, AI_AUTO_GROUP],
  };
  config["proxy-groups"].splice(aiIndex, 0, aiStable, aiAuto, scholar);

  ai.proxies = [AI_STABLE_GROUP, AI_AUTO_GROUP];
  for (const key of [
    "include-all",
    "include-all-proxies",
    "include-all-providers",
    "filter",
    "exclude-filter",
    "exclude-type",
    "default-selected",
    "empty-fallback",
  ]) delete ai[key];

  const choices = Array.isArray(fallback.proxies) ? fallback.proxies : [];
  fallback.proxies = ["DIRECT", ...choices.filter((choice) => choice !== "DIRECT")];
  delete fallback["default-selected"];
}

function configureRules(config) {
  if (!Array.isArray(config.rules)) throw new Error("subscription must contain a rules array");
  const custom = new Set(CUSTOM_RULES);
  const customRuleKey = (rule) => {
    if (typeof rule !== "string") return null;
    const parts = rule.split(",").map((part) => part.trim());
    if (parts.length < 2 || ![
      "DOMAIN",
      "DOMAIN-SUFFIX",
      "DOMAIN-KEYWORD",
      "DOMAIN-WILDCARD",
      "DOMAIN-REGEX",
      "IP-CIDR",
      "IP-CIDR6",
      "SRC-IP-CIDR",
      "DST-PORT",
      "SRC-PORT",
      "PROCESS-NAME",
      "PROCESS-PATH",
      "NETWORK",
      "GEOIP",
      "GEOSITE",
    ].includes(parts[0].toUpperCase())) return null;
    const key = parts.slice(0, 2);
    if (parts[parts.length - 1] === "no-resolve") key.push("no-resolve");
    return key.join(",");
  };
  const customKeys = new Set(CUSTOM_RULES.map(customRuleKey));
  const original = config.rules.filter(
    (rule) => typeof rule !== "string" || !(
      custom.has(rule) ||
      rule.startsWith("RULE-SET,Custom-") ||
      customKeys.has(customRuleKey(rule))
    ),
  );
  config.rules = [...CUSTOM_RULES, ...original];
}

function validateResult(config) {
  const groups = config["proxy-groups"];
  const names = groups.map((group) => group && group.name);
  if (names.some((name, index) => !name || names.indexOf(name) !== index)) {
    throw new Error("proxy group names must be present and unique");
  }
  for (const required of [
    AI_STABLE_GROUP,
    AI_AUTO_GROUP,
    AI_GROUP,
    SCHOLAR_GROUP,
    FALLBACK_GROUP,
  ]) {
    if (!names.includes(required)) throw new Error(`generated group is missing: ${required}`);
  }
  if (!groupByName(config, AI_STABLE_GROUP).proxies.length ||
      !groupByName(config, AI_AUTO_GROUP).proxies.length) {
    throw new Error("AI stable/backup group is empty");
  }
  const expectedAiChoices = [AI_STABLE_GROUP, AI_AUTO_GROUP];
  if (JSON.stringify(groupByName(config, AI_GROUP).proxies) !==
      JSON.stringify(expectedAiChoices)) {
    throw new Error("Ai+ does not prefer stable selection");
  }
  if (JSON.stringify(groupByName(config, SCHOLAR_GROUP).proxies) !==
      JSON.stringify(expectedAiChoices)) {
    throw new Error("academic search does not share the stable AI exit");
  }
  if (groupByName(config, FALLBACK_GROUP).proxies[0] !== "DIRECT") {
    throw new Error("漏网之鱼 does not prefer DIRECT");
  }
  if (config.rules.length < CUSTOM_RULES.length ||
      !CUSTOM_RULES.every((rule, index) => config.rules[index] === rule)) {
    throw new Error("custom rule priority is invalid");
  }
}

function main(config) {
  const original = config;
  try {
    if (!config || typeof config !== "object") throw new Error("invalid subscription config");
    const next = JSON.parse(JSON.stringify(config));
    fixProviderPaths(next);
    configureGroups(next);
    configureRules(next);
    validateResult(next);
    return next;
  } catch (error) {
    if (typeof console !== "undefined" && typeof console.error === "function") {
      console.error(`[FlClash rules] extension skipped: ${error.message}`);
    }
    return original;
  }
}
