// Generated by clash.py. Edit rules/*.yaml, not this file.
// Clash Verge Rev subscription extension script; no network requests or secrets.

const CUSTOM_RULES = __CUSTOM_RULES_JSON__;
const AI_GROUP = "Ai+";
const AI_AUTO_GROUP = "Ai自动选择";
const SCHOLAR_GROUP = "学术搜索";
const FALLBACK_GROUP = "漏网之鱼";

// Bound short country codes to avoid matching ordinary words that contain hk/mo/tw.
const AI_EXCLUDE = /(?:🇭🇰|🇲🇴|🇹🇼|香港|澳门|澳門|台湾|台灣|hong[ -]?kong|macau|macao|taiwan|(?:^|[^a-z])(?:hk|mo|tw)(?:[^a-z]|$)|剩余流量|流量剩余|到期时间|过期时间|重置时间|套餐提示|订阅信息|(?:^|[\s|_-])(?:expire|traffic|sync|reset|官网|套餐|订阅|更新|客服|网址)(?:[\s:：|_-]|$))/i;

function groupByName(config, name) {
  return config["proxy-groups"].find((group) => group && group.name === name);
}

function eligibleAiNodes(config) {
  const seen = new Set();
  return config.proxies
    .filter((proxy) => proxy && typeof proxy.name === "string" && proxy.name)
    .filter((proxy) => String(proxy.type || "").toLowerCase() !== "direct")
    .map((proxy) => proxy.name)
    .filter((name) => !AI_EXCLUDE.test(name))
    .filter((name) => {
      if (seen.has(name)) return false;
      seen.add(name);
      return true;
    });
}

function fixProviderPaths(config) {
  const providers = config["rule-providers"];
  if (!providers || typeof providers !== "object") return;
  const apple = providers.Apple;
  const appleDev = providers.AppleDev;
  if (apple && appleDev && apple.path && apple.path === appleDev.path) {
    apple.path = "./providers/rule/Apple.yaml";
  }
}

function configureGroups(config) {
  if (!Array.isArray(config.proxies) || !Array.isArray(config["proxy-groups"])) {
    throw new Error("subscription must contain proxies and proxy-groups arrays");
  }

  const groups = config["proxy-groups"];
  const ai = groupByName(config, AI_GROUP);
  const fallback = groupByName(config, FALLBACK_GROUP);
  if (!ai || !fallback) {
    throw new Error(`subscription is missing ${!ai ? AI_GROUP : FALLBACK_GROUP}`);
  }

  const nodes = eligibleAiNodes(config);
  if (!nodes.length) throw new Error("no eligible non-HK/MO/TW AI nodes remain");

  config["proxy-groups"] = groups.filter(
    (group) => group && group.name !== AI_AUTO_GROUP && group.name !== SCHOLAR_GROUP,
  );
  const aiIndex = config["proxy-groups"].findIndex((group) => group.name === AI_GROUP);

  const aiAuto = {
    name: AI_AUTO_GROUP,
    type: "url-test",
    proxies: [...nodes],
    url: "http://www.gstatic.com/generate_204",
    interval: 300,
    tolerance: 20,
    lazy: true,
  };
  const scholar = {
    name: SCHOLAR_GROUP,
    type: "select",
    // Select and keep one explicit node in the client; Ai自动选择 is only fallback.
    proxies: [AI_AUTO_GROUP, ...nodes],
  };
  config["proxy-groups"].splice(aiIndex, 0, aiAuto, scholar);

  ai.proxies = [AI_AUTO_GROUP, ...nodes];
  for (const key of [
    "include-all",
    "include-all-proxies",
    "include-all-providers",
    "filter",
    "exclude-filter",
    "exclude-type",
    "default-selected",
    "empty-fallback",
  ]) delete ai[key];

  const choices = Array.isArray(fallback.proxies) ? fallback.proxies : [];
  fallback.proxies = ["DIRECT", ...choices.filter((choice) => choice !== "DIRECT")];
  delete fallback["default-selected"];
}

function configureRules(config) {
  if (!Array.isArray(config.rules)) throw new Error("subscription must contain a rules array");
  const custom = new Set(CUSTOM_RULES);
  const original = config.rules.filter(
    (rule) => typeof rule !== "string" || !custom.has(rule),
  );
  config.rules = [...CUSTOM_RULES, ...original];
}

function validateResult(config) {
  const groups = config["proxy-groups"];
  const names = groups.map((group) => group && group.name);
  if (names.some((name, index) => !name || names.indexOf(name) !== index)) {
    throw new Error("proxy group names must be present and unique");
  }
  for (const required of [AI_AUTO_GROUP, AI_GROUP, SCHOLAR_GROUP, FALLBACK_GROUP]) {
    if (!names.includes(required)) throw new Error(`generated group is missing: ${required}`);
  }
  if (!groupByName(config, AI_AUTO_GROUP).proxies.length) {
    throw new Error("Ai自动选择 is empty");
  }
  if (groupByName(config, AI_GROUP).proxies[0] !== AI_AUTO_GROUP) {
    throw new Error("Ai+ does not prefer Ai自动选择");
  }
  if (groupByName(config, FALLBACK_GROUP).proxies[0] !== "DIRECT") {
    throw new Error("漏网之鱼 does not prefer DIRECT");
  }
  if (config.rules.length < CUSTOM_RULES.length ||
      !CUSTOM_RULES.every((rule, index) => config.rules[index] === rule)) {
    throw new Error("custom rule priority is invalid");
  }
}

function main(config) {
  const original = config;
  try {
    if (!config || typeof config !== "object") throw new Error("invalid subscription config");
    const next = JSON.parse(JSON.stringify(config));
    fixProviderPaths(next);
    configureGroups(next);
    configureRules(next);
    validateResult(next);
    return next;
  } catch (error) {
    if (typeof console !== "undefined" && typeof console.error === "function") {
      console.error(`[FlClash rules] extension skipped: ${error.message}`);
    }
    return original;
  }
}
